Repository fga-eps-mds/2024.2-LIVRO-LIVRE-API, pull requests merged in 2024-12, with the labels that each got.

#23 Solve Autenticar Usuario
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dtos/signInResponse.dto.ts
  src/auth/dtos/signUp.dto.ts
  src/database/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: US, MDS

#21 feat: create a method put to update users
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.constants.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dtos/signIn.dto.ts
  src/database/config.ts
  src/database/entities/user.entity.ts
  src/users/dtos/createUser.dto.ts
  src/users/dtos/updateUser.dto.ts
  src/users/users.controller.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/database/utils.ts
Labels: FEATURE

#26 feat: fix some issues
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/users/users.controller.ts
Labels: MAJOR RELEASE
